name: emm
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohttp=3.9.5
  - aiosignal=1.3.1
  - attrs=23.2.0
  - aws-c-auth=0.7.22
  - aws-c-cal=0.6.14
  - aws-c-common=0.9.19
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.1
  - aws-c-io=0.14.8
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.5.9
  - aws-c-sdkutils=0.1.16
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.26.9
  - aws-sdk-cpp=1.11.329
  - blas=1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2024.2.2
  - certifi=2024.2.2
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - datasets=2.19.1
  - dill=0.3.8
  - ffmpeg=4.3
  - filelock=3.14.0
  - freetype=2.12.1
  - frozenlist=1.4.1
  - gflags=2.2.2
  - glog=0.7.0
  - gmp=6.3.0
  - gmpy2=2.1.5
  - gnutls=3.6.13
  - huggingface_hub=0.23.0
  - icu=73.2
  - idna=3.7
  - intel-openmp=2023.1.0
  - jinja2=3.1.4
  - jpeg=9e
  - keyutils=1.6.1
  - krb5=1.21.2
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20240116.2
  - libarrow=16.1.0
  - libarrow-acero=16.1.0
  - libarrow-dataset=16.1.0
  - libarrow-substrait=16.1.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.9.1.3
  - libcurand=10.3.5.147
  - libcurl=8.8.0
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=13.2.0
  - libgoogle-cloud=2.24.0
  - libgoogle-cloud-storage=2.24.0
  - libgrpc=1.62.2
  - libhwloc=2.10.0
  - libiconv=1.17
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - libnghttp2=1.58.0
  - libnpp=11.8.0.86
  - libnsl=2.0.1
  - libnvjpeg=11.9.0.86
  - libparquet=16.1.0
  - libpng=1.6.43
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - libsqlite=3.45.3
  - libssh2=1.11.0
  - libstdcxx-ng=13.2.0
  - libthrift=0.19.0
  - libtiff=4.5.0
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libwebp-base=1.4.0
  - libxcrypt=4.4.36
  - libxml2=2.12.7
  - libzlib=1.2.13
  - llvm-openmp=15.0.7
  - lz4-c=1.9.4
  - markupsafe=2.1.5
  - mkl=2023.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.0.5
  - multiprocess=0.70.16
  - ncurses=6.5
  - nettle=3.6
  - networkx=3.3
  - numpy=1.26.4
  - openh264=2.1.1
  - openjpeg=2.5.0
  - openssl=3.3.0
  - orc=2.0.1
  - packaging=24.0
  - pandas=2.2.2
  - pillow=10.3.0
  - pip=24.0
  - pyarrow=16.1.0
  - pyarrow-core=16.1.0
  - pyarrow-hotfix=0.6
  - pysocks=1.7.1
  - python=3.12.3
  - python-dateutil=2.9.0
  - python-tzdata=2024.1
  - python-xxhash=3.4.1
  - python_abi=3.12
  - pytorch=2.3.0
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pyyaml=6.0.1
  - re2=2023.09.01
  - readline=8.2
  - regex=2024.5.15
  - requests=2.32.2
  - s2n=1.4.15
  - safetensors=0.4.3
  - setuptools=70.0.0
  - six=1.16.0
  - snappy=1.2.0
  - sympy=1.12
  - tbb=2021.12.0
  - tk=8.6.13
  - tokenizers=0.19.1
  - torchaudio=2.3.0
  - torchvision=0.18.0
  - tqdm=4.66.4
  - transformers=4.41.1
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024a
  - urllib3=2.2.1
  - wheel=0.43.0
  - xxhash=0.8.2
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.4
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - fsspec==2024.5.0
      - huggingface-hub==0.23.2
      - scipy==1.13.1
      - termcolor==2.4.0
      - timm==1.0.4.dev0
      - yacs==0.1.8
