# AUG:
AUG_AUTO_AUGMENT: rand-m9-mstd0.5-inc1  
AUG_COLOR_JITTER: 0.4  
AUG_CUTMIX: 1.0
AUG_CUTMIX_MINMAX: null
AUG_MIXUP: 0.0  
AUG_MIXUP_MODE: batch
AUG_MIXUP_PROB: 1.0  
AUG_MIXUP_SWITCH_PROB: 0.5  
AUG_RECOUNT: 1
AUG_REMODE: pixel
AUG_REPROB: 0.25  
BASE:
- ""
# DATA:
DATA_BATCH_SIZE: 1048
DATA_DATASET: cifar10  
DATA_DATA_PATH: images  
DATA_IMG_SIZE: 32  
DATA_INTERPOLATION: bicubic  
DATA_MASK_PATCH_SIZE: 32  
DATA_MASK_RATIO: 0.6  
DATA_MASK_STRAT: random  
DATA_PIN_MEMORY: true  
EVAL_MODE: false  
LOCAL_RANK: 0  
# MODEL:
MODEL_DROP_PATH_RATE: 0.1  
MODEL_DROP_RATE: 0.0 
MODEL_LABEL_SMOOTHING: 0.1 
MODEL_NAME: vit_scratch_finetune  
MODEL_NUM_CLASSES: 10
MODEL_TYPE: vit
# MODEL_VIT:
MODEL_VIT_EMBED_DIM: 768
MODEL_VIT_PATCH_SIZE: 4
MODEL_VIT_DEPTH: 6
MODEL_VIT_NUM_HEADS: 12
MODEL_VIT_USE_APE: False
MODEL_VIT_USE_RPB: True
MODEL_VIT_USE_SHARED_RPB: False
MODEL_VIT_USE_MEAN_POOLING: True
PRETRAINED: ""   
PRINT_FREQ: 50   
SAVE_FREQ: 100 
SEED: 0 
TAG: finetune_vit_scratch_cifar_gimini_v5_wandb_sweep
# TRAIN:
TRAIN_ACCUMULATION_STEPS: 0  
TRAIN_BASE_LR: 0.00255859375
TRAIN_CLIP_GRAD: 5 
TRAIN_EPOCHS: 45 
TRAIN_LAYER_DECAY: 0.65  
TRAIN_WARMUP_EPOCHS: 5
TRAIN_LR_SCHEDULER_DECAY_EPOCHS: 25  
TRAIN_LR_SCHEDULER_DECAY_RATE: 0.1  
TRAIN_LR_SCHEDULER_GAMMA: 0.1 
TRAIN_LR_SCHEDULER_MULTISTEPS: []  
TRAIN_LR_SCHEDULER_NAME: cosine  
TRAIN_MIN_LR: 5.117187499999999e-07  
# TRAIN_OPTIMIZER:
TRAIN_OPTIMIZER_BETAS:
- 0.9  
- 0.999   
TRAIN_OPTIMIZER_EPS: 1.0e-8   
TRAIN_OPTIMIZER_MOMENTUM: 0.9   
TRAIN_OPTIMIZER_NAME: adamw
TRAIN_AUTO_RESUME: False
AMP: True
PATIANCE: 3