#MODEL
MODEL_TYPE: vit
MODEL_NAME: simmim_pretrain
MODEL_DROP_PATH_RATE: 0.1
MODEL_VIT_EMBED_DIM: 768
MODEL_VIT_PATCH_SIZE: 4
MODEL_VIT_DEPTH: 6
MODEL_VIT_NUM_HEADS: 12
MODEL_VIT_USE_APE: False
MODEL_VIT_USE_RPB: True
MODEL_VIT_USE_SHARED_RPB: False
#DATA
DATA_BATCH_SIZE: 1024 #for random 512 is 11.6GB, for expanding 128 is 11.6GB 
DATA_IMG_SIZE: 32
DATA_MASK_STRAT: expand
DATA_DATASET: cifar10
DATA_DATA_PATH: images  
#TRAIN
TRAIN_EPOCHS: 800
TRAIN_WARMUP_EPOCHS: 10
TRAIN_BASE_LR: 0.0001
TRAIN_WARMUP_LR: 0.0000005
TRAIN_WEIGHT_DECAY: 0.05
TRAIN_LR_SCHEDULER_NAME: 'multistep'
TRAIN_LR_SCHEDULER_GAMMA: 0.1
TRAIN_LR_SCHEDULER_MULTISTEPS: [700,]
PRINT_FREQ: 24
SAVE_FREQ: 20
TAG: simmim_exp_pretrain__vit_base__cifar__800ep